In [1]:
import numpy as np
import pandas as pd

In [5]:
A = np.arange(21, 30).reshape(3, 3)
A

array([[21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [6]:
# interchange the rows and columns
A.transpose()

array([[21, 24, 27],
       [22, 25, 28],
       [23, 26, 29]])

In [8]:
# matrix miltiplication
B = np.arange(21, 30).reshape(3, 3)
C = np.arange(31, 40).reshape(3, 3)

B.dot(C)

array([[2250, 2316, 2382],
       [2556, 2631, 2706],
       [2862, 2946, 3030]])

In [9]:
# multiple matrix multiplications
D = np.arange(21, 30).reshape(3, 3)
E = np.arange(31, 40).reshape(3, 3)
F = np.arange(41, 50).reshape(3, 3)

tempA = D.dot(E).dot(F)
tempA

array([[306108, 313056, 320004],
       [347742, 355635, 363528],
       [389376, 398214, 407052]])

In [10]:
tempB = D.dot(E.dot(F))
tempB

array([[306108, 313056, 320004],
       [347742, 355635, 363528],
       [389376, 398214, 407052]])

300